version: '3.7'

services:
  # nginx:
  #   image: nginx:1.17
  #   volumes:
  #     - "./nginx/conf.d:/etc/nginx/conf.d:ro"
  #     - "./websh_front/public:/var/www:ro"
  #   ports:
  #     - "80:80"
  #   network_mode: "host"

  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
      - "./volumes/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: kintai
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
