version: '3.7'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - "./volumes/nginx/conf.d:/etc/nginx/conf.d:ro"
    ports:
      - "80:80"
    network_mode: "host"

  db:
    image: postgres:13-alpine
    ports:
      - '15432:5432'
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
      - "./volumes/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: kintai
      POSTGRES_USER: kintai
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
